# Generated by Django 2.1.15 on 2022-06-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=16, verbose_name='课程名')),
                ('cpno', models.CharField(max_length=16, null=True, verbose_name='先修课程')),
                ('ccredit', models.IntegerField(default=60, verbose_name='课程学分')),
            ],
        ),
        migrations.CreateModel(
            name='sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=60, verbose_name='课程分数')),
                ('scno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=16, verbose_name='学生姓名')),
                ('stuphone', models.CharField(max_length=16, verbose_name='学生电话')),
                ('stuaddress', models.CharField(max_length=16, verbose_name='学生地址')),
                ('stucollege', models.CharField(max_length=16, verbose_name='学生院系')),
                ('stumajor', models.CharField(max_length=16, verbose_name='学生专业')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='sc',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StuInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='sc',
            unique_together={('sid', 'scno')},
        ),
    ]
